export const data = [
  {
    num: 1,
    browser: 'Chrome',
    visits: '۲۵۵',
    dataInPercentage: 90,
    imgSrc: '/vector/dashboard/browsers/chrome.png',
  },
  {
    num: 2,
    browser: 'Safari',
    visits: '۲۰۰',
    dataInPercentage: 80,
    imgSrc: '/vector/dashboard/browsers/safari.png',
  },
  {
    num: 3,
    browser: 'Firefox',
    visits: '۱۵۰',
    dataInPercentage: 70,
    imgSrc: '/vector/dashboard/browsers/firefox.png',
  },
  {
    num: 4,
    browser: 'Edge',
    visits: '۱۰۰',
    dataInPercentage: 60,
    imgSrc: '/vector/dashboard/browsers/edge.png',
  },
  {
    num: 5,
    browser: 'Opera',
    visits: '۵۰',
    dataInPercentage: 50,
    imgSrc: '/vector/dashboard/browsers/opera.png',
  },
  {
    num: 6,
    browser: 'Brave',
    visits: '۳۰',
    dataInPercentage: 40,
    imgSrc: '/vector/dashboard/browsers/brave.png',
  },
  {
    num: 7,
    browser: 'vivaldi',
    visits: '۲۵۵',
    dataInPercentage: 30,
    imgSrc: '/vector/dashboard/browsers/vivaldi.png',
  },
  {
    num: 8,
    browser: 'UC Browser',
    visits: '۱۰',
    dataInPercentage: 20,
    imgSrc: '/vector/dashboard/browsers/uc.png',
  },
]
