export const data = [
  {
    num: 1,
    osName: 'Windows',
    visits: '۲۵۵',
    dataInPercentage: 90,
    imgSrc: '/vector/dashboard/os/windows.png',
  },
  {
    num: 2,
    osName: 'Mac',
    visits: '۲۰۰',
    dataInPercentage: 80,
    imgSrc: '/vector/dashboard/os/mac.png',
  },
  {
    num: 3,
    osName: 'Ubuntu',
    visits: '۱۵۰',
    dataInPercentage: 70,
    imgSrc: '/vector/dashboard/os/ubuntu.png',
  },
  {
    num: 4,
    osName: 'Chrome',
    visits: '۱۰۰',
    dataInPercentage: 60,
    imgSrc: '/vector/dashboard/browsers/chrome.png',
  },
  {
    num: 5,
    osName: 'Cent',
    visits: '۵۰',
    dataInPercentage: 50,
    imgSrc: '/vector/dashboard/os/cent.png',
  },
  {
    num: 6,
    osName: 'Linux',
    visits: '۳۰',
    dataInPercentage: 40,
    imgSrc: '/vector/dashboard/os/linux.png',
  },
  {
    num: 7,
    osName: 'Fedora',
    visits: '۲۵۵',
    dataInPercentage: 30,
    imgSrc: '/vector/dashboard/os/fedora.png',
  },
  {
    num: 8,
    osName: 'Vivaldi',
    visits: '۱۰',
    dataInPercentage: 20,
    imgSrc: '/vector/dashboard/os/vivaldi-os.png',
  },
]
